### ISSUE TITLE
Ability to add arbitrary data to Widget Definition Objects

### ISSUE THREAD

**Issue by robertmazzo** [DataTorrent/malhar-angular-dashboard#112] opened 2015-01-30 15:47 UTC
Hello,
I think my problem is simple. I have added a property to my Widget Definitions called `'gadgetConfigured'`.
I simply want to expose `'widget.gadgetConfigured'` to the main Dashboard.html template using the ng-if directive as follows :

        <div ng-if="widget.gadgetConfigured" class="panel-body widget-content"  ng-style="widget.contentStyle"></div>

which should then either "remove or recreate the portion of the DOM" as per Angular (https://docs.angularjs.org/api/ng/directive/ngIf)

However the behavior is inconsistent. More specifically, when gadgetConfigured is set to true, then my widget content is NOT rendered. It's totally blank.

Here's the 'chart_area' widget def in the WidgetDefinitions factory:

        { // either one will work: template (directly embed the html) or templateUrl (embed the html file path)
              name: 'chart_area',
              title: 'Area Chart',            
              templateUrl: 'app/shared/gadget-templates/chart-area.html',
              size: size,
              dataModelType: ColumnChartDataModel,
              initImage: 'chart_area.jpg',
              gadgetConfigured: true,
          }

and here's an image showing how I am debugging in my gadgetModel.js, within the init() function. To the right you can see gadgetConfigured is true.

![dash-templ](https://cloud.githubusercontent.com/assets/8823366/5978483/1bd96576-a86e-11e4-87fc-b6845ecfd4e3.png)

![dash-widg-empty](https://cloud.githubusercontent.com/assets/8823366/5978443/d0ef279e-a86d-11e4-9077-1a5003decd2e.png)

Perhaps I'm missing something, or my use of ng-if is wrong; but I'm banging my head wondering where I'm going wrong.

thanks in advance,
Bob

**Comment by andyperlitch** [comment] 2015-02-01 15:48
Hey @robertmazzo,

Figured out your issue, and am considering making some changes to the tool because of it. Currently, **widgets do not inherit arbitrary data from their widget definition objects**, only  [whitelisted properties](https://github.com/DataTorrent/malhar-angular-dashboard/blob/master/src/models/widgetModel.js#L23-L38). But that code is messy and could be cleaned up significantly.

I think your use-case is valid enough for me to change the library and support arbitrary data on widget definition objects. Hang tight, I'll try and churn something out this weekend.

**Comment by andyperlitch** [comment] 2015-02-01 18:14
@robertmazzo I have created a new milestone called v1.0.0, and I'll try to address this issue there. I am going to rename this if you dont mind so that it works better as a milestone item.

**Comment by andyperlitch** [comment] 2015-02-01 18:31
Relates to #62

**Comment by robertmazzo** [comment] 2015-02-02 00:46
Thank you Andy for your attention to this.
Best regards 
Bob

**Comment by robertmazzo** [comment] 2015-02-03 21:14
Hi Andy,
You mentioned that only whitelisted properties would get inherited by the widgets.
So if I add a couple of properties to the WidgetModel as such, should this work ? 

     function WidgetModel(Class, overrides) {
          var defaults = {
              title: 'Dashboard Rept',
              name: Class.name,
              attrs: Class.attrs,
              dataAttrName: Class.dataAttrName,
              dataModelType: Class.dataModelType,
              dataModelArgs: Class.dataModelArgs, // used in data model constructor, not serialized
              //AW Need deep copy of options to support widget options editing
              dataModelOptions: Class.dataModelOptions,
              settingsModalOptions: Class.settingsModalOptions,
              onSettingsClose: Class.onSettingsClose,
              onSettingsDismiss: Class.onSettingsDismiss,
              style: Class.style || {},
              size: Class.size || {},
              enableVerticalResize: (Class.enableVerticalResize === false) ? false : true,
              initImage: Class.initImage,    // added new initial image to display - BM:
              gadgetConfigured: Class.gadgetConfigured
          };

**Comment by andyperlitch** [comment] 2015-02-10 18:08
(sorry for the delayed response) Yea this should work

**Comment by robertmazzo** [comment] 2015-02-11 15:04
Andy,
I've had problems trying to show/hide the `widget-content` div using `ng-if`, however I'll keep experimenting with this:

           <div ng-if="widget.gadgetConfigured" class="panel-body widget-content"  ng-style="widget.contentStyle"></div>

I'll close the ticket in the meantime.
thanks

**Comment by andyperlitch** [comment] 2015-02-11 16:59
Hm, not sure what could be going wrong here. Again, this is something I will (hopefully) be taking up very soon here.

**Comment by andyperlitch** [comment] 2015-02-11 20:59
actually reopening so this remains an issue to address for the v1.0.0 milestone

**Comment by andyperlitch** [comment] 2015-02-11 21:01
realized this was duplicate of #62

**Closed** 2015-02-11 21:01 UTC
