### ISSUE TITLE
How to make a widget full screen   and then back orginal position by click a imag on widget

### ISSUE THREAD

**Issue by xiaomingwang1234** [DataTorrent/malhar-angular-dashboard#173] opened 2016-05-27 19:01 UTC
How to make a widget full screen   and then back orginal position by click a imag on widget

**Comment by awashbrook** [comment] 2016-05-27 19:34
Probably a duplicate of #48 which is currently being worked on.

**Comment by wvary** [comment] 2016-10-03 21:44
As awashbrook said, it's a duplicate of #48.

**Closed by wvary** 2016-10-03 21:44 UTC
Labels: duplicate
